# Generated by Django 4.2.24 on 2025-09-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image", name="name", field=models.CharField(max_length=255),
        ),
    ]
