# Generated by Django 5.2.6 on 2025-09-15 13:30

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
    ]
